# Generated by Django 4.1.5 on 2023-03-24 16:02

from django.db import migrations, models
import task_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(null=True, upload_to=task_manager.models.image_file),
        ),
    ]
